name: "Solar Dashboard"
version: "1.0.0"
slug: "solar_dashboard"
description: "Simple solar power system dashboard"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8099/tcp: 8099
webui: "http://[HOST]:[PORT:8099]"
